{% set name = "solo-epd-loader" %}
{% set version = "0.4.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/solo_epd_loader-{{ version }}.tar.gz
  sha256: d0fa297d97db77134222a8e3d2e83ca7c2e56ec7b48b25f043a48479421c1645

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - astropy-base
    - cdflib
    - numpy
    - pandas
    - python >={{ python_min }}
    - sunpy >=3.1.3
    - tqdm

test:
  imports:
    - solo_epd_loader
    - solo_epd_loader.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jgieseler/solo-epd-loader
  summary: Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  description: |
    Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  license: BSD-3-Clause
  license_file:
    - licenses/LICENSE.rst
    - licenses/TEMPLATE_LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
