{% set name = "solo-epd-loader" %}
{% set version = "0.4.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/solo_epd_loader-{{ version }}.tar.gz
  sha256: 9c4d7b4e05373bf1d72cddab9e3a1f515e3885480773e47ea9e18e589db82ed1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
  run:
    - astropy-base
    - cdflib
    - numpy
    - pandas
    - python >={{ python_min }}
    - sunpy >=4.1.0
    - tqdm

test:
  imports:
    - solo_epd_loader
    - solo_epd_loader.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jgieseler/solo-epd-loader
  summary: Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  description: |
    Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  license: BSD-3-Clause
  license_file:
    - licenses/LICENSE.rst
    - licenses/TEMPLATE_LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
