{% set name = "solo-epd-loader" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solo_epd_loader-{{ version }}.tar.gz
  sha256: 7e444f3211a3faf3e454f97e60fe14bd2b0ec75a5156648ea3993a5daaa106eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - astropy
    - cdflib
    - numpy
    - pandas
    - python >=3.6
    - sunpy >=3.1.3
    - tqdm

test:
  imports:
    - solo_epd_loader
    - solo_epd_loader.tests
  requires:
    - pip

about:
  home: https://github.com/jgieseler/solo-epd-loader
  summary: Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  description: |
    Data loader for Solar Orbiter/EPD energetic charged particle sensors EPT, HET, and STEP.
  license: BSD-3-Clause
  license_file:
    - licenses/LICENSE.rst
    - licenses/TEMPLATE_LICENSE.rst

extra:
  recipe-maintainers:
    - jgieseler
